force-app/main/default/objects/Service_Info__c/Service_Info__c.object-meta.xml
<CustomObject>
    <description>Stores configuration data for Elevate services.</description>
    <label>Service Info</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Service Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Info__c/fields/Is_Secret__c.field-meta.xml
<CustomField>
    <fullName>Is_Secret__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the Key and Value are secret.</description>
    <inlineHelpText>Denotes whether the Key and Value are secret.</inlineHelpText>
    <label>Is Secret</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Info__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The name of a piece of configuration data from Elevate. It&#39;s associated value is stored in the Value__c field.</description>
    <inlineHelpText>The name of a piece of configuration data from Elevate. It&#39;s associated value is stored in the Value__c field.</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Info__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <description>The name of the Elevate service the Key and Value are associated with.</description>
    <inlineHelpText>The name of the Elevate service the Key and Value are associated with.</inlineHelpText>
    <label>Service</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Info__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of a piece of configuration data from Elevate. It&#39;s associated name is stored in the key__c field.</description>
    <inlineHelpText>The value of a piece of configuration data from Elevate. It&#39;s associated name is stored in the key__c field.</inlineHelpText>
    <label>Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ServiceInfoUtils_TEST.cls
@isTest
public with sharing class ServiceInfoUtils_TEST {
    @isTest
    static void testCreateServiceInfo() {
        Test.startTest();
        Service_Info__c newServiceInfo = ServiceInfoUtils.createServiceInfo('testService', 'key', 'value', false);

        System.assertEquals('testService', newServiceInfo.Service__c);
        System.assertEquals('key', newServiceInfo.Key__c);
        System.assertEquals('value', newServiceInfo.Value__c);
        System.assertEquals(false, newServiceInfo.Is_Secret__c);
        Test.stopTest();
    }

    @isTest
    static void testGetAllData() {
        TestUtils_TEST.createTestServiceInfoData();

        Test.startTest();

        Map<String, String> allServiceInfo = ServiceInfoUtils.getAllData('testService');


        System.assertEquals(2, allServiceInfo.size());

        System.assertEquals(true, allServiceInfo.containsKey('key1'));
        System.assertEquals(true, allServiceInfo.containsKey('key2'));

        System.assertEquals('value1', allServiceInfo.get('key1'));
        System.assertEquals('value2', allServiceInfo.get('key2'));
        Test.stopTest();
    }

    @isTest
    static void testGetSensitiveData() {
        TestUtils_TEST.createTestServiceInfoData();

        Test.startTest();
        Map<String, String> allServiceInfo = ServiceInfoUtils.getAllSensitiveData('testService');

        
        System.assertEquals(1, allServiceInfo.size());

        System.assertEquals(true, allServiceInfo.containsKey('key1'));

        System.assertEquals('value1', allServiceInfo.get('key1'));
        Test.stopTest();
    }

    @isTest
    static void testGetNonsensitiveData() {
        TestUtils_TEST.createTestServiceInfoData();

        Test.startTest();
        Map<String, String> allServiceInfo = ServiceInfoUtils.getAllNonsensitiveData('testService');

        
        System.assertEquals(1, allServiceInfo.size());

        System.assertEquals(true, allServiceInfo.containsKey('key2'));

        System.assertEquals('value2', allServiceInfo.get('key2'));
        Test.stopTest();
    }

    
}